[package]
name = "graphics"
version = "0.1.0"
authors = ["Arif Roktim <aroktim@stuy.edu>"]
edition = "2018"

[dependencies]
lib_graphics = { path = "../lib_graphics" }
parse_graphics = { path = "../parse_graphics" }
