#!/bin/bash
set -E

function usage {
    cat 1>&2 <<EOF
usage: new_assignment [help] [<assignment name>]
Create a new branch and modify Cargo.toml for a new assignment

Options:
    help                    Show this help
    <assignment name>       Setup everything for a new assignment
EOF
}

function cleanup {
    usage
    exit 1
}

trap usage ERR

function new {
    git checkout -b "$1"
}

if [[ $# -ne 1 ]]; then
    cleanup
fi

case "$1" in
    help | --help)
        usage
        ;;
    --*)
        cleanup
        ;;
    *)
        new "$1"
        ;;
esac
