#!/bin/bash

function usage {
    cat 1>&2 <<EOF
Create a new branch and modify Cargo.toml for a new assignment

usage: new_assignment [help] [<assignment name>]
    help                  Show this help
    <assignment name>     Setup everything for a new assignment
EOF
}

function new {
    git checkout -b "$1"
    rm -f Cargo.lock
    sed -i.bak 's/\(name = \)".*"/\1"'"$1"'"/' Cargo.toml
}

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

case "$1" in
    help)
        usage
        ;;
    *)
        new "$1"
        ;;
esac
